language: node_js
node_js:
  - "8"
  - "6"
  - "node"
env:
  - WEBPACK_VERSION=4 DEVSERVER_VERSION=2

install:
  - npm install -g codecov
  - npm install
  - npm install webpack@$WEBPACK_VERSION webpack-dev-server@$DEVSERVER_VERSION
script:
  - npm run test:coverage
  - codecov
